import type { Metadata } from 'next'
import '@repo/ui/styles.css'
import './globals.css'
import { Saira_Semi_Condensed } from 'next/font/google'
import { ReactNode } from 'react'

const saira = Saira_Semi_Condensed({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-saira',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={saira.className}>{children}</body>
    </html>
  )
}
